#!/bin/sh
#
# Copyright (c) 2003-2004 E. Will et al.
# Rights to this code are documented in doc/LICENSE.
#
# This file is a script for svn commit.
#
# $$Id$
#

svn log -vrHEAD:1 > ChangeLog
svn commit --editor-cmd=vi

exit 0
