#!/bin/sh
#
# Copyright (c) 2003-2011 Eric Will <rakaur@malkier.net>
# Rights to this code are documented in doc/LICENSE.
#
# This file indents all of the source code using gindent.
#

cd inc; gindent *.h; rm *~; cd ..
cd src; gindent *.c; rm *~; cd ..

exit 0
